# Generated by Django 2.2.3 on 2019-07-03 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='observers',
            field=models.ManyToManyField(related_name='observers', to=settings.AUTH_USER_MODEL),
        ),
    ]
